Repository Priyansusahoo/BlueComet, pull requests merged in 2025-03, with the labels that each got.

#3 Feature/swagger implementation
  event-planner/pom.xml
  event-planner/src/main/java/com/bluecomet/event_planner/config/OpenAPIConfig.java
  event-planner/src/main/java/com/bluecomet/event_planner/controller/EventController.java
  event-planner/src/main/java/com/bluecomet/event_planner/repository/EventRepository.java
  event-planner/src/main/java/com/bluecomet/event_planner/service/EventService.java
Labels: enhancement, feature

#5 bug(api) : getEventsBetweenDates() - EventController class
  event-planner/src/main/java/com/bluecomet/event_planner/controller/EventController.java
Labels: bug, good first issue

#13 Document Java code for better maintainability, readability.
  event-planner/src/main/java/com/bluecomet/event_planner/config/OpenAPIConfig.java
  event-planner/src/main/java/com/bluecomet/event_planner/controller/EventController.java
  event-planner/src/main/java/com/bluecomet/event_planner/dto/event/EventRequest.java
  event-planner/src/main/java/com/bluecomet/event_planner/dto/event/EventResponse.java
  event-planner/src/main/java/com/bluecomet/event_planner/dto/request/EventDateRangeRequest.java
  event-planner/src/main/java/com/bluecomet/event_planner/entity/Event.java
  event-planner/src/main/java/com/bluecomet/event_planner/enums/EventStatus.java
  event-planner/src/main/java/com/bluecomet/event_planner/repository/EventRepository.java
  event-planner/src/main/java/com/bluecomet/event_planner/service/EventService.java
  event-planner/src/main/java/com/bluecomet/event_planner/utils/api/ApiErrorResponse.java
  event-planner/src/main/java/com/bluecomet/event_planner/utils/customexceptions/EventAlreadyCancelledException.java
  event-planner/src/main/java/com/bluecomet/event_planner/utils/customexceptions/EventNotFoundException.java
  event-planner/src/main/java/com/bluecomet/event_planner/utils/customexceptions/globalexceptionhandler/GlobalExceptionHandler.java
  event-planner/src/main/java/com/bluecomet/event_planner/utils/mapper/EventMapper.java
Labels: documentation, enhancement

#19 Document/swagger-OpenApi docs event registration controller
  event-planner/src/main/java/com/bluecomet/event_planner/controller/EventController.java
  event-planner/src/main/java/com/bluecomet/event_planner/controller/EventRegistrationController.java
  event-planner/src/main/java/com/bluecomet/event_planner/service/event_registration/EventRegistrationServiceImpl.java
Labels: documentation, enhancement

#25 Document (Project Doc): updated readme with latest tech stack
  README.md
Labels: documentation
